### ISSUE TITLE
Deployment/release upgradability problem

### ISSUE THREAD

**Issue by rigo101** [sanghanet/sanghanet#2]
In the current architecture we have a data loss problem in case of release upgrade/deployment.

User’s avatars are deleted at the moment in case of new deployment.
Release update should work w/o data loss.

**Comment by DenesDanko** [comment]
Solution is a workaround.
1. There is  service endpoint on BE: '/images/list'.
2. a deployment runs a wget operation to download images before delete the AZURE instance.

This method works only on AZURE (live) deployment!
