### ISSUE TITLE
At new registration the finance data are not initialized properly

### ISSUE THREAD

**Issue by rigo101** [sanghanet/sanghanet#24]
After a new member registers, initial financial data is generated.
However, searching users in Finance Admin page crashes.
Suspected cause: financial data document is not complete or malformed.

After running 'npm run buildfinance',  there is no more crash on search ( quick workaround, until fix provided:) ).

**Comment by DenesDanko** [comment]
Analizaltam a problemat.
Komoly koncepcionalis hiba van: a Fin. Admin UserName-eket ker a DB-tol kereseshez, viszont az AddMember NEM csinal userName attributumot a DB-ben a Financeaccounts store-ba tett dokumentumokba!

Hogy eddig miert mukodott? Azert mert a testData generator script viszont csinal userName-et. 

Megoldasok:
1) email-re keresni, vagy
2) az SU oldal Name attributumat beirni a finance adatokhoz. 

Volt arrol szo korabban hogy a nevegyezesek (Nagy Peter lehet tobb is) miatt nev+email lenne jo a keresesekhez.
De ezt csak a testrelease utan lenne jo megcsinalni, amikor attesszunk kereseseket a BE-re.
Addig talan megteszi a 2)-es megoldas..
