### ISSUE TITLE
Finance Admin, select new user DOES NOT update summary cards.

### ISSUE THREAD

**Issue by DenesDanko** [sanghanet/sanghanet#31]
**Describe the bug**
Finance Admin, select new user DOES NOT update summary cards!
Finance data updated according expectations.

**To Reproduce**
1. Login w/ Finance Admin
2. Search d, and select Denes
3. Search again another user and select that user.
4. Summary cards hold the values of the FIRST selected user.

**Expected behavior**
Summary card data as well should updated after new user selected.

**Device, OS, browser specifics if needed**
Linux & Chrome, but I guess It is not platform specific bug.

**Comment by rigo101** [comment]
Forced re-render of FinanceDashboard when new member selected
