### ISSUE TITLE
Double check: all strings translation have to be done.

### ISSUE THREAD

**Issue by DenesDanko** [sanghanet/sanghanet#33]
Some errors(system errors mostly) can not be translated.

**Comment by DenesDanko** [comment]
Member page:
  'Showing all members'
Footer:
  'Made by'
Finance admin:
  'No user selected'

**Comment by rigo101** [comment]
Translation of Members page is completed

**Comment by rigo101** [comment]
Translation of Footer is completed

**Comment by KristofNalesnyik** [comment]
Done
