### ISSUE TITLE
FE: finance admin search modification

### ISSUE THREAD

**Issue by sn-dev-team** [sanghanet/sanghanet#5]
Search should work alphabetic way:

‘W' => only names (first and last names as well) started with 'W’
ABC sorted
discard accented characters
https://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript

Once you selected a member from the list, the data of the given user should be automatically displayed. Currently you have to hit the Select button which is counterintuitive.
‌
Hits shall be weighted based on relevance and sorted.

**Comment by JoBenjamin** [comment]
Resolved by fa-select-refactor #22
