### ISSUE TITLE
Investigate Emergency contact name behavior.

### ISSUE THREAD

**Issue by DenesDanko** [sanghanet/sanghanet#51]
A vész esetén értesítendőnél nem esett le, hogy az angol szerinti névsorrendet kellene követnem, azaz keresztnév után vezetéknév. Kellett kis idő, mire leesett, miért nem fogadta el.

**Comment by KristofNalesnyik** [comment]
Magyarázatot kérek, hogy miért nem fogadta el a nevet. (kutassuk fel az illetőt)
Biztosan nem volt ilyen feature, ami ezt okozhatta. Vagy bug volt, vagy typo.
A névvalidációt töröltük, csak a min 2 karakter követelmény maradt. Szerintem zárhatjuk ezt a ticketet.

**Comment by DenesDanko** [comment]
Szerintem nem kell megkeresni senkit. Ki lett veve a validacio, az kezel minden ilyen problemat.
