### ISSUE TITLE
Finance, deleted items display.

### ISSUE THREAD

**Issue by DenesDanko** [sanghanet/sanghanet#68]
Szerintem tök jó lenne, ha alapvetően valami kis ikonnal oldalt lehetne szűrni, hogy megjelenítse a törölt tételeket, vagy ne.

Megmarad minden, amit beírtam, csak áthúzva. Ugye ezt még törlitek majd?

User - no deleted items
F Admin - checkbox to filter out deleted items.

**Comment by KristofNalesnyik** [comment]
Implemented in PR #95
